blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/Aaron-Wickham/backdrp_fm/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/Aaron-Wickham/backdrp_fm/blob/main/README.md
    about: Read the project documentation
