// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcDo2ALK6qTYtEmO3jxMwKadDljXK6m8g',
    appId: '1:858745330379:web:75ee185b8c370408ffd94e',
    messagingSenderId: '858745330379',
    projectId: 'backdrp-fm-dev',
    authDomain: 'backdrp-fm-dev.firebaseapp.com',
    storageBucket: 'backdrp-fm-dev.firebasestorage.app',
    measurementId: 'G-F7VD9RT3W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLIfGq1GNHAEroYenMBVf5wr47-_p8UM',
    appId: '1:858745330379:android:affc1e47dcb1fea8ffd94e',
    messagingSenderId: '858745330379',
    projectId: 'backdrp-fm-dev',
    storageBucket: 'backdrp-fm-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthhsGyIlrcQQvb0DhqJDrI2jP5Y79RT8',
    appId: '1:858745330379:ios:76b2dc9419ddff08ffd94e',
    messagingSenderId: '858745330379',
    projectId: 'backdrp-fm-dev',
    storageBucket: 'backdrp-fm-dev.firebasestorage.app',
    iosBundleId: 'com.backdrpfm.app.dev',
  );
}
