// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW2NDu5KORksksXoe2Py7In1uveo7JboM',
    appId: '1:639126146221:web:f5cb0d1b5cfdd8b5868a24',
    messagingSenderId: '639126146221',
    projectId: 'backdrop-fm',
    authDomain: 'backdrop-fm.firebaseapp.com',
    storageBucket: 'backdrop-fm.firebasestorage.app',
    measurementId: 'G-FVNDC15TC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0R2NOUFI3F15ibc7VYvd59ZPDbMFVvE',
    appId: '1:639126146221:android:c649be8668d84500868a24',
    messagingSenderId: '639126146221',
    projectId: 'backdrop-fm',
    storageBucket: 'backdrop-fm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-GFVO2-8ZH2VjMGrMIjdI76qcSyJAfrY',
    appId: '1:639126146221:ios:0505fdbdf6de0752868a24',
    messagingSenderId: '639126146221',
    projectId: 'backdrop-fm',
    storageBucket: 'backdrop-fm.firebasestorage.app',
    iosBundleId: 'com.backdrpfm.app',
  );
}
