// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRBYQDyzoIaDI9-KMVzMXdGqg6MBXw1VU',
    appId: '1:180438727971:web:00bbaba42cfd81c1fa6096',
    messagingSenderId: '180438727971',
    projectId: 'backdrp-fm-staging',
    authDomain: 'backdrp-fm-staging.firebaseapp.com',
    storageBucket: 'backdrp-fm-staging.firebasestorage.app',
    measurementId: 'G-40J950CMVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPny7IIe4PIiAKiMXyDLDmGZ1eyRihsQ',
    appId: '1:180438727971:android:fc1b9aa646298028fa6096',
    messagingSenderId: '180438727971',
    projectId: 'backdrp-fm-staging',
    storageBucket: 'backdrp-fm-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGlaNQRGmWOc2PClnfGLhsic4NS8-kAE',
    appId: '1:180438727971:ios:3e91f923f51e67fffa6096',
    messagingSenderId: '180438727971',
    projectId: 'backdrp-fm-staging',
    storageBucket: 'backdrp-fm-staging.firebasestorage.app',
    iosBundleId: 'com.backdrpfm.app.staging',
  );
}
