// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdPNGRIC2WJvZym3DwmX5ltGvoFCHXHzY',
    appId: '1:864187672865:web:df50f3c56f524b7ec1f660',
    messagingSenderId: '864187672865',
    projectId: 'backdrp-fm-prod-4215e',
    authDomain: 'backdrp-fm-prod-4215e.firebaseapp.com',
    storageBucket: 'backdrp-fm-prod-4215e.firebasestorage.app',
    measurementId: 'G-DP5GPMX5ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtxt6Lksf72aaFYI2p0nJtWY1X0_L5q1Q',
    appId: '1:864187672865:android:5aea51778aa320f9c1f660',
    messagingSenderId: '864187672865',
    projectId: 'backdrp-fm-prod-4215e',
    storageBucket: 'backdrp-fm-prod-4215e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDThLlu-Lq6S4zF0pHRMteZA98UjmhWdrg',
    appId: '1:864187672865:ios:2cdfb900ad18bfbdc1f660',
    messagingSenderId: '864187672865',
    projectId: 'backdrp-fm-prod-4215e',
    storageBucket: 'backdrp-fm-prod-4215e.firebasestorage.app',
    iosBundleId: 'com.backdrpfm.app',
  );
}
