name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze:
    name: Analyze & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Create placeholder env files
        run: |
          echo "ENVIRONMENT=development" > .env.development
          echo "ENVIRONMENT=staging" > .env.staging
          echo "ENVIRONMENT=production" > .env.production

      - name: Run unit tests
        run: flutter test --coverage --reporter=expanded

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Create placeholder env files
        run: |
          echo "ENVIRONMENT=development" > .env.development
          echo "ENVIRONMENT=staging" > .env.staging
          echo "ENVIRONMENT=production" > .env.production

      - name: Create Firebase config from secrets
        run: |
          echo "${{ secrets.IOS_FIREBASE_CONFIG }}" | base64 -d > ios/Runner/GoogleService-Info.plist

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Create placeholder env files
        run: |
          echo "ENVIRONMENT=development" > .env.development
          echo "ENVIRONMENT=staging" > .env.staging
          echo "ENVIRONMENT=production" > .env.production

      - name: Create Firebase config from secrets
        run: |
          echo "${{ secrets.ANDROID_FIREBASE_CONFIG }}" | base64 -d > android/app/google-services.json

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Create placeholder env files
        run: |
          echo "ENVIRONMENT=development" > .env.development
          echo "ENVIRONMENT=staging" > .env.staging
          echo "ENVIRONMENT=production" > .env.production

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
