name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-test:
    name: Integration Tests (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.9.2'
          channel: 'stable'
          cache: true

      - name: Setup Node.js (for Firebase Emulators)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Start Firebase Emulators
        run: |
          firebase emulators:start --only auth,firestore,storage &
          # Wait for emulators to be ready
          sleep 15

      - name: Run Integration Tests
        run: |
          flutter test integration_test/ \
            -d macos \
            --dart-define=USE_FIREBASE_EMULATORS=true \
            --dart-define=ENVIRONMENT=development

      - name: Stop Firebase Emulators
        if: always()
        run: |
          pkill -f firebase-emulator || true

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-failures
          path: integration_test/failures/
